# Generated by Django 6.0.3 on 2026-09-16 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('enrollment_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('student_type', models.CharField(choices=[('DAY_SCHOLAR', 'Day Scholar'), ('BOARDER', 'Boarder')], default='DAY_SCHOLAR', max_length=20)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
