# Generated by Django 6.0.3 on 2026-09-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_attendance_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='scan_method',
            field=models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('MANUAL', 'Manual'), ('OFFLINE', 'Offline')], default='FINGERPRINT', max_length=20),
        ),
    ]
