# Generated by Django 6.0.3 on 2026-09-18 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_scan_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('finger', models.CharField(choices=[('LEFT_THUMB', 'Left Thumb'), ('LEFT_INDEX', 'Left Index'), ('RIGHT_THUMB', 'Right Thumb'), ('RIGHT_INDEX', 'Right Index')], max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_id', 'finger'), name='unique_student_fingerprint')],
            },
        ),
    ]
